
version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Alfonso
      - APELLIDO=Amezqueta
      - DOCUMENTO=37228817
      - NACIMIENTO=1992-12-07
      - NUMERO=12345
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Cosme
      - APELLIDO=Fulanito
      - DOCUMENTO=33445566
      - NACIMIENTO=1994-11-12
      - NUMERO=11111
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Homero
      - APELLIDO=Simpson
      - DOCUMENTO=11223344
      - NACIMIENTO=1980-07-19
      - NUMERO=33213
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml


  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Gabriel
      - APELLIDO=Fisher
      - DOCUMENTO=34723434
      - NACIMIENTO=1985-05-01
      - NUMERO=49023
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Jorge
      - APELLIDO=Perez
      - DOCUMENTO=39129268
      - NACIMIENTO=1989-11-11
      - NUMERO=123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789000000
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
